In [1]:
import torch

cm = torch.tensor([[ 20,   8,   1,   0],
                   [  5, 242,  79,   0],
                   [  4,  44, 283,   4],
                   [  1,   1,  11,  17]])
cm

tensor([[ 20,   8,   1,   0],
        [  5, 242,  79,   0],
        [  4,  44, 283,   4],
        [  1,   1,  11,  17]])

In [2]:
p, n = cm.vsplit(2)
TN, FP = p.hsplit(2)
FN, TP = n.hsplit(2)
# cm2 = torch.tensor([[TN, FP],[FN, TP]])
# cm2

TN, FP, FN, TP = TN.sum(), FP.sum(), FN.sum(), TP.sum()
cm2 = torch.tensor([[TN, FP],[FN, TP]])
cm2

tensor([[275,  80],
        [ 50, 315]])

In [3]:
cm2.diag() / cm2.sum(1)

tensor([0.7746, 0.8630])

In [ ]:
cm2.diag().sum() / cm2.sum()


tensor(0.8194)

In [7]:
for row in cm:
    for c in row:
        print(c.item(), end=' ')
    print()

20 8 1 0 
5 242 79 0 
4 44 283 4 
1 1 11 17 
